pipersjames/t3a2react-app

README.md
package-lock.json
package.json
src/App.js
src/components/CreateAccount.jsx
src/index.js

installed react-router-dom and route structure

route implementation

---

package-lock.json
package.json
src/components/LoginForm.jsx

installed package for handling cookies securely and added some logic for form submission that has been commented out pending the URL for the Server

cookie package and login logic

---

src/components/CreateAccount.jsx
src/components/LoginForm.jsx

account creation

---

README.md
src/components/CreateAccount.jsx
src/index.js

input type changes, readme additions, react-dom

patch: quickfixes

---

package-lock.json
package.json
src/components/Navbar.jsx

hamburger icon work using useState

navbar with bootstrap

---

src/components/AccordionTable.jsx
src/components/FullNameInput.jsx
src/pages/FormBuilder.jsx

need tolook into drag and cancel and so on

drag and drop

---

src/App.css
src/App.js
src/components/AuthChecker.jsx
src/components/CreateAccount.jsx

redirects when invalid token to login page

added auth redirect

---

src/App.js
src/components/AuthChecker.jsx
src/components/CreateAccount.jsx
src/components/LoginForm.jsx
src/components/Navbar.jsx

added cookie removal on logout to remove jwt. changed navigation route names to start app at login

logout functionality

---

package-lock.json
package.json
src/pages/Forms.jsx

having error 404, not being able to fetch from the /formTemplates/forms as per formTemplateController.jsx

trialling, trying to fetch data from the backend to frontend

---

src/components/FillOutForm.jsx
src/pages/HomePage.jsx
src/tests/FormsPage.test.js

linting fixes

---

src/components/FillOutForm.jsx
src/components/formComponents/FullNameInput.jsx
src/components/formComponents/Label.jsx
src/components/formComponents/ShortQA.jsx
src/pages/FormBuilder.jsx

added functionality for changing the headers and saving to the database.

ShortQA title functionality

---

README.md
src/components/FillOutForm.jsx
src/components/formComponents/ShortQA.jsx
src/pages/FormBuilder.jsx

added functionality for changing the question of the Short QA. adjusted Formbuilder accordingly

short QA fix

---

src/components/FillOutForm.jsx
src/pages/FormBuilder.jsx

form submission handle

---

src/components/FillOutForm.jsx
src/components/formComponents/LongQA.jsx
src/components/formComponents/ShortQA.jsx
src/pages/FormBuilder.jsx

passes name to filloutform pages

fixed name passing

---

src/components/formComponents/LongQA.jsx
src/components/formComponents/ShortQA.jsx

patched up fillout form labels

---

package-lock.json
package.json
src/App.css
src/components/FillOutForm.jsx
src/components/formComponents/LongQA.jsx
src/pages/FormsPage.jsx

added created forms render on forms page

table formpage

---

src/components/FillOutForm.jsx
src/contexts/ApiProvider.jsx
src/contexts/FavouritesProvider.jsx
src/index.js

moved favourites functionality into context so other components of the app can access

favourites context established

---

src/components/AuthChecker.jsx
src/components/FillOutForm.jsx
src/contexts/FormTemplateProvider.jsx
src/pages/FormBuilder.jsx

preview and preview button in form builder, adjusted form creation syntax for a few items

added preview and minor tweaks

---

src/App.css
src/components/FavouriteForms.jsx
src/components/FillOutForm.jsx
src/pages/ActionsPage.jsx
src/pages/FormBuilder.jsx
src/pages/FormsPage.jsx
src/pages/HomePage.jsx

styling adjustments

---

src/components/ActionsMenu.jsx
src/pages/ActionsPage.jsx
src/pages/FormsPage.jsx

fixed a crash that happened when no records where found to iterate through  and render a table.

fix: actions menu

---

src/contexts/FormTemplateProvider.jsx
src/pages/FormBuilder.jsx

was rendering old data from previous previews.

fix: state delayed update  with formbuilder preview
